export const developmentAPIs = {
  login: "http://localhost/unmg_pms/api/signInUser.php",
  register: "http://localhost/unmg_pms/api/registerUser.php",
  updateUser: "http://localhost/unmg_pms/api/updateUser.php",
  uploadProfilePicture: "http://localhost/unmg_pms/api/uploadImage.php",
  uploadBatchUsers: "http://localhost/unmg_pms/api/batchUpload.php",
  retrieveUsers: "http://localhost/unmg_pms/api/retrieveUsers.php",
  manageCompany: "http://localhost/unmg_pms/api/manageCompany.php",
  conglomerate: "http://localhost/unmg_pms/api/conglomerate.php",
  userActions: "http://localhost/unmg_pms/api/userActions.php",
  saveDate: "http://localhost/unmg_pms/api/saveDate.php",
  fetchOverview:"http://localhost/unmg_pms/api/fetchOverview.php",
  formCreation:"http://localhost/unmg_pms/api/formCreation.php",
  updateGoals:"http://localhost/unmg_pms/api/updateGoals.php",
  sendMail:"http://localhost/unmg_pms/api/sendmail.php",
  fetchAllGoals: "http://localhost/unmg_pms/api/fetchAllGoals.php",
  fetchDashboardData: "http://localhost/unmg_pms/api/fetchDashboardData.php",
  getEmployeeGoals: "http://localhost/unmg_pms/api/getEmployeeGoals.php",
  approveGoals: "http://localhost/unmg_pms/api/approveGoals.php",
  retrieveTrackingScores:"http://localhost/unmg_pms/api/retrieveTrackingScores.php",
  userSubmitAchievements:"http://localhost/unmg_pms/api/userSubmitAchievements.php",
  retrieveTracking:"http://localhost/unmg_pms/api/retrieveTracking.php",
  userSubmitTrackingEmployee: "http://localhost/unmg_pms/api/userSubmitTrackingEmployee.php",
  retrievePillars: "http://localhost/unmg_pms/api/retrievePillars.php",
  retrieveKPIDescAndPillarPercentage: "http://localhost/unmg_pms/api/retrieveKpiDescAndPillarPercentage.php",
  retrieveEvaluation: "http://localhost/unmg_pms/api/retrieveEvaluation.php",
  retrieveTrackingEmployee: "http://localhost/unmg_pms/api/retrieveTrackingEmployee.php",
  retrieveSignOff: "http://localhost/unmg_pms/api/retrieveSignOff.php",
  retrieveSignOffEmployee: "http://localhost/unmg_pms/api/retrieveSignOffEmployee.php",
  fetchKPIDuration: "http://localhost/unmg_pms/api/fetchKpiDuration.php",
  retrieveGlobalSettings: "http://localhost/unmg_pms/api/retrieveGlobalSettings.php",
  retrieveReceivers: "http://localhost/unmg_pms/api/retrieveReceivers.php",
  retrieveConversations: "http://localhost/unmg_pms/api/retrieveConversations.php",

  };

export const releaseAPIs = {
  login: "../api/signInUser.php",
  register: "../api/registerUser.php",
  updateUser: "../api/updateUser.php",
  uploadProfilePicture: "../api/uploadImage.php",
  uploadBatchUsers: "../api/batchUpload.php",
  retrieveUsers: "../api/retrieveUsers.php",
  manageCompany: "../api/manageCompany.php",
  conglomerate: "../api/conglomerate.php",
  userActions: "../api/userActions.php",
  saveDate: "../api/saveDate.php",
  fetchOverview:"../api/fetchOverview.php",
  fetchDashboardData:"../api/fetchDashboardData.php",
  formCreation:"../api/formCreation.php",
  updateGoals:"../api/updateGoals.php",
  sendMail:"../api/sendmail.php",
  fetchAllGoals: "../api/fetchAllGoals.php",
  getEmployeeGoals: "../api/getEmployeeGoals.php",
  approveGoals: "../api/approveGoals.php",
  retrieveTrackingScores:"../api/retrieveTrackingScores.php",
  userSubmitAchievements:"../api/userSubmitAchievements.php",
  retrieveTracking:"../api/retrieveTracking.php",
  userSubmitTrackingEmployee: "../api/userSubmitTrackingEmployee.php",
  retrievePillars: "../api/retrievePillars.php",
  retrieveKPIDescAndPillarPercentage: "../api/retrieveKpiDescAndPillarPercentage.php",
  retrieveEvaluation: "../api/retrieveEvaluation.php",
  retrieveTrackingEmployee: "../api/retrieveTrackingEmployee.php",
  retrieveSignOff: "../api/retrieveSignOff.php",
  retrieveSignOffEmployee: "../api/retrieveSignOffEmployee.php",
  fetchKPIDuration: "../api/fetchKpiDuration.php",
  retrieveGlobalSettings: "../api/retrieveGlobalSettings.php",
  retrieveReceivers: "../api/retrieveReceivers.php",
  retrieveConversations: "../api/retrieveConversations.php",
};
