<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap");

        * {
            font-family: 'Open Sans', Arial, Helvetica, sans-serif;
        }

        :root {
            --un-blue: #183145;
            --bg-default: #efedf8;
            --bg-default-dark: #dbd8eb;
        }

        a {
            text-decoration: none;
            color: black;
        }

        img {
            height: 50px;
        }

        .im {
            color: black !important;
        }

        div.container {
            max-width: 90%;
        }
        @media screen and (min-width: 1024px) {
            div.container {
            max-width: 60%;
        }
        }
    </style>
</head>

<body style="background-color: #efedf8; padding: 16px;">
    <div class="container" style="margin: auto; background-color: white; padding: 10px;">
        <section style="text-align:center; border-bottom: 2px solid #dbd8eb; line-height: 20px;">
            <img src="https://lh3.googleusercontent.com/drive-viewer/AITFw-wRWtrB5Q-S_Z_KPqp6dtCiWs97Y0G2ChCQ1C573PtNVUNE-LEyTkHp8YgDAD-qEWz0rBbvEdo20baT8_BHQU9mz_u46A=s1600" alt="">
            <p style="color: black; font-weight: 600; font-size: 1.1rem;">United Neon Media Group <br>
                Performance Management System</p>
        </section>
        <section style="padding: 0px 16px 12px;">
            <div>
                <p style="font-weight: 600; color: black; text-align: center;">New Notification!</p>
                <p style="margin: 0; color: black;">Greetings, {receipient}!</p>
                <article style="padding-left: 1rem;">
                    <p style="margin: 0; padding-top: 5px; color: black;">{message}</p>
                    <div>
                        <p style="color: black;"><span style="font-weight: 600; color: black;">Employee Name: </span><span style="color: black;">{employee_name}</span><br>
                            <span style="font-weight: 600; color: black;">Date: </span>{date_submitted}
                        </p>
                    </div>
                    <a href="{link}" style="text-decoration: underline;">{link_message}</a>
                </article>
                <p style="font-size: 13px; margin-bottom: 0; color: #8f89ae;">This email is automatically generated by the UNMG PMS. Please do not reply.</p>
            </div>
        </section>
    </div>
    <section style="text-align:center; color: #8f89ae;">
        <p class="copyright">© <?php echo date('Y'); ?> <a style="color: #8f89ae;" href="https://www.unitedneonmediagroup.com">United Neon Media Group</a>. All rights reserved.<br>
            2nd Flr. HPL Building, #60 Sen. Gil Puyat Ave., Makati City, 1200 Philippines</p>
    </section>
</body>